#!/usr/bin/env bash
set -e

MSG=${1:-}

if [ -z "$MSG" ]; then
  echo "❌ Nhập message commit"
  exit 1
fi

git add .
git commit -m "$MSG"

BRANCH=$(git branch --show-current)

git push origin "$BRANCH"

echo "💾 Đã lưu: $MSG"
